# Generated by Django 5.0.1 on 2024-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bodybuilder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("DB", "Dumbbell"),
                    ("BB", "Barbell"),
                    ("MC", "Machine"),
                    ("BW", "Bodyweight"),
                    ("OT", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
