# Generated by Django 5.0.1 on 2024-02-23 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bodybuilder", "0005_bodyworkout_rename_exercise_bodyexercise_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkoutExercise",
            new_name="BodyWorkoutExercise",
        ),
    ]
