# Generated by Django 5.0.1 on 2024-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bodybuilder", "0006_rename_workoutexercise_bodyworkoutexercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyexercise",
            name="slug",
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
