# Generated by Django 5.0.1 on 2024-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0007_alter_bodyexercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyexercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
