# Generated by Django 5.0.1 on 2024-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0008_alter_bodyexercise_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodyWorkoutExercise',
            new_name='WorkoutExercise',
        ),
    ]
