# Generated by Django 5.0.2 on 2024-03-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0009_rename_bodyworkoutexercise_workoutexercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_Exercise_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.CharField(choices=[('Dumbbell', 'Dumbbell'), ('Barbell', 'Barbell'), ('Machine', 'Machine'), ('Bodyweight', 'Bodyweight'), ('Other', 'Other')], max_length=100)),
                ('reps', models.IntegerField()),
                ('series', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Exercise_Bodybuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodybuilder.body_exercise_workout')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodybuilder.bodyworkout')),
            ],
        ),
        migrations.AlterField(
            model_name='bodyworkout',
            name='exercises',
            field=models.ManyToManyField(through='bodybuilder.Workout_Exercise_Bodybuilding', to='bodybuilder.body_exercise_workout'),
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
