# Generated by Django 5.0.2 on 2024-03-12 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0010_body_exercise_workout_workout_exercise_bodybuilding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='body_exercise_workout',
            name='rep_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='body_exercise_workout',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_body_exercise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bodyexercise',
            name='rep_max',
            field=models.FloatField(blank=True),
        ),
    ]
