# Generated by Django 5.0.1 on 2024-02-20 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrosWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("FT", "For Time"),
                            ("AMRAP", "As Many Rounds as Possible"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rounds", models.IntegerField(blank=True, null=True)),
                ("time_cap", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="CrossExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Kettlebell", "Kettlebell"),
                            ("Bodyweight", "Bodyweight"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("rep_max", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_for_women", models.FloatField()),
                ("weight_for_men", models.FloatField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crossfit.crossexercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crossfit.crosworkout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crosworkout",
            name="exercises",
            field=models.ManyToManyField(
                through="crossfit.WorkoutExercise", to="crossfit.crossexercise"
            ),
        ),
    ]
