# Generated by Django 5.0.1 on 2024-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crossfit", "0002_crosworkout_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="reps",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="weight_for_men",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="weight_for_women",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
