# Generated by Django 5.0.1 on 2024-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crossfit", "0002_crosworkout_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossexercise",
            name="rep_max",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
