# Generated by Django 5.0.1 on 2024-02-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0003_alter_crossexercise_rep_max'),
        ('crossfit', '0003_workoutexercise_reps_and_more'),
    ]

    operations = [
    ]
